name: Cherrypick merged pull request
on:
  push:
      branches:
        - master
  pull_request_target:
    branches: [master]
    types: [closed]
  issue_comment:
    types: [created]

jobs:    
  cherrypick:
    name: Cherrypick pull request
    runs-on: ubuntu-latest
    # Only run when pull request is merged
    # or when a comment starting with `/cherrypick` is created by someone other than the
    # https://github.com/backport-action bot user (user id: 97796249). Note that if you use your
    # own PAT as `github_token`, that you should replace this id with yours.
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged &&
        github.event.pull_request.milestone != null
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 97796249 &&
        startsWith(github.event.comment.body, '/cherrypick')
      )
    steps:
      - name: Setup constants
        id: check_constants
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            pr_url="${{ github.event.issue.pull_request.url }}"
            pr_number=$(echo "$pr_url" | grep -oE '[0-9]+$')
            echo "PR Number: $pr_number"
            echo "User ID: ${{github.event.comment.user.id}}"
            echo "Getting PR URL"
            curl "https://api.github.com/repos/DynamoDS/TempTestAutomation/pulls/$pr_number" | jq '.milestone.title' | sed -e 's/"/ /g' | sed 's/ //g' > milestone.out
            milestone=$(cat milestone.out)
            echo "Milestone: $milestone"
            echo "milestone=$milestone" >> "$GITHUB_OUTPUT"
          fi
          if [[ "${{ github.event_name }}" == "pull_request_target" ]]; then
            milestone=${{github.event.pull_request.milestone}}
            echo "Milestone: $milestone"
            echo "milestone=$milestone" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
      - name: Check if RC branch exists for the milestone
        id: check_branch
        run: |
          BRANCH_NAME="RC${{ steps.check_constants.outputs.milestone }}.0_master"
          echo "Branch name: $BRANCH_NAME"
          BRANCH_URL="https://api.github.com/repos/${{ github.repository }}/branches/RC${{ steps.check_constants.outputs.milestone }}.0_master"
          curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/branches/RC${{ steps.check_constants.outputs.milestone }}.0_master > branch_response.out
          branch_response=$(cat branch_response.out)
          echo $branch_response
          if [ $branch_response -eq 200 ]; then
            echo "Branch exists"
          else
            echo "Branch does not exist"
